swagger: "2.0"
info:
  version: "0.0.1"
  title: Logbook service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/entries:
    x-swagger-router-controller: entries
    get:
      description: Returns log entries to the caller
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetEntriesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Add a new log entry
      operationId: addEntry
      consumes:
        - application/json
      parameters:
        - in: body
          name: result
          required: true
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  value:
                    $ref: "#/definitions/Entry"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SingleEntryResponse"
            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Entry:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
        description: JsonAPI object type
      attributes:
        type: object
        properties:
          created-at:
            type: string
            description: timestamp when this entry was created
          elapsed-time: 
            type: number
            description: The amount of time recorded for this entry
        required:
          - created-at
    required:
      - type
      - attributes
  GetEntriesResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/Entry"
    required:
      - data
  SingleEntryResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/Entry"
    required:
      - data
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
